### ISSUE TITLE
[개발] 움직이는 배경 개발

### ISSUE THREAD

**Issue by Masarica1** [tan-games/game_development#1]
# 개발 기능: 움직이는 배경

**개발 위치**
source/background.py

**사용 리소스**
resource/backgrounds/*

**세부 구조**
배경 사진이 오른쪽에서 나타나 왼쪽으로 움직이고, 배경 사진의 끝에는 다른 사진이 연결되어 자연스럽게 이어지도록 해야 함

**추가 사항**
없음

**Comment by myjju4208** [comment]
쓰읍 그럿케하는거아닌대 저한태좀베우시죠 기분나쁘셨으면제송합니다((퍼퍼버버벅
